const MATCH_I18N = {
  ru: { brandSub:'Match Center', navHome:'Главная', navPlay:'Играть', navLeaderboard:'Лидерборд', navProfile:'Профиль', matchCenter:'Match Center', matchResult:'Результат матча', matchNotFound:'Матч не найден', invalidMatch:'Укажи корректный id матча в адресе.', winner:'Победитель', defeat:'Поражение', draw:'Ничья', pending:'Ожидание', map:'Карта', duration:'Длительность', playedAt:'Дата', teamA:'Team A', teamB:'Team B', players:'Игроки', matchMvp:'MVP матча', mvpUnavailable:'MVP недоступен', kills:'Убийства', deaths:'Смерти', assists:'Ассисты', kd:'K/D', headshots:'Headshots', damage:'Урон', roundMvps:'Round MVPs', firstKills:'First kills', clutches:'Клатчи', eloBefore:'Elo до', eloAfter:'Elo после', eloChange:'Elo change', roundHistory:'История раундов', allRounds:'Все', detailedUnavailable:'Подробная история раундов недоступна', retry:'Повторить', loading:'Загрузка', stillProgress:'Матч ещё идёт', season:'Сезон', status:'Статус' },
  en: { brandSub:'Match Center', navHome:'Home', navPlay:'Play', navLeaderboard:'Leaderboard', navProfile:'Profile', matchCenter:'Match Center', matchResult:'Match result', matchNotFound:'Match not found', invalidMatch:'Provide a valid match id in the URL.', winner:'Winner', defeat:'Defeat', draw:'Draw', pending:'Pending', map:'Map', duration:'Duration', playedAt:'Played at', teamA:'Team A', teamB:'Team B', players:'Players', matchMvp:'Match MVP', mvpUnavailable:'MVP unavailable', kills:'Kills', deaths:'Deaths', assists:'Assists', kd:'K/D', headshots:'Headshots', damage:'Damage', roundMvps:'Round MVPs', firstKills:'First kills', clutches:'Clutches', eloBefore:'Elo before', eloAfter:'Elo after', eloChange:'Elo change', roundHistory:'Round history', allRounds:'All rounds', detailedUnavailable:'Detailed round history unavailable', retry:'Retry', loading:'Loading', stillProgress:'Match is still in progress', season:'Season', status:'Status' }
};
let lang = localStorage.getItem(TrustApi.langKey) === 'en' ? 'en' : 'ru';
let currentMatch = null; let roundFilter = 'all'; let activeController = null;
const $ = (id) => document.getElementById(id); const t = (k) => MATCH_I18N[lang]?.[k] || MATCH_I18N.ru[k] || k; const esc = TrustApi.escapeHtml;
function txt(id, v) { const el = $(id); if (el) el.textContent = v; } function show(id, on) { $(id)?.classList.toggle('hidden', !on); }
function profileUrl(p) { const id = p?.steamId || p?.steamId64 || p?.steam_id; return id ? `./profile.html?steamId=${encodeURIComponent(id)}` : './profile.html'; }
function eloDelta(p) { if (p?.eloChange != null) return p.eloChange; const before = TrustApi.optionalNumber(p?.eloBefore); const after = TrustApi.optionalNumber(p?.eloAfter); return before != null && after != null ? after - before : null; }
function teamOf(p) { return String(p?.team || p?.teamName || p?.side || '').toUpperCase().includes('B') ? 'B' : 'A'; }
function playersOf(match) { return Array.isArray(match?.players) ? match.players : Array.isArray(match?.playerStats) ? match.playerStats : []; }
function scores(match) { return { a: TrustApi.safeNumber(match?.teamAScore ?? match?.scoreA, 0), b: TrustApi.safeNumber(match?.teamBScore ?? match?.scoreB, 0) }; }
function winner(match) { const w = String(match?.winnerTeam || match?.winner || '').toUpperCase(); if (w === 'A' || w === 'B') return w; const s = scores(match); if (String(match?.status).toLowerCase() !== 'completed') return null; if (s.a === s.b) return 'draw'; return s.a > s.b ? 'A' : 'B'; }
function applyLang() { document.documentElement.lang = lang; Object.entries({ matchBrandSub:'brandSub', matchNavHome:'navHome', matchNavPlay:'navPlay', matchNavLeaderboard:'navLeaderboard', matchNavProfile:'navProfile', matchMobileNavHome:'navHome', matchMobileNavPlay:'navPlay', matchMobileNavLeaderboard:'navLeaderboard', matchMobileNavProfile:'navProfile', matchCenterBadge:'matchCenter', matchResultTitle:'matchResult', roundHistoryTitle:'roundHistory', roundFilterAll:'allRounds', roundFilterA:'teamA', roundFilterB:'teamB', matchRetryBtn:'retry' }).forEach(([id,k]) => txt(id, t(k))); $('matchLangRu')?.classList.toggle('active', lang === 'ru'); $('matchLangEn')?.classList.toggle('active', lang === 'en'); if (currentMatch) render(currentMatch); }
function renderHero(m) { const s = scores(m); const win = winner(m); const complete = String(m.status || '').toLowerCase() === 'completed'; txt('matchStatusPill', m.status || t('pending')); const meta = [`${t('map')}: ${TrustApi.formatMapName(m.map || m.mapName)}`, `${t('playedAt')}: ${TrustApi.formatDate(m.completedAt || m.finishedAt || m.startedAt, lang)}`, `${t('duration')}: ${TrustApi.formatDuration(m.durationSeconds ?? m.durationSec)}`]; if (m.season) meta.push(`${t('season')}: ${m.season}`); $('matchMeta').innerHTML = meta.map((x) => `<span class="pill idle">${esc(x)}</span>`).join(''); const labelA = !complete ? t('pending') : win === 'draw' ? t('draw') : win === 'A' ? t('winner') : t('defeat'); const labelB = !complete ? t('pending') : win === 'draw' ? t('draw') : win === 'B' ? t('winner') : t('defeat'); $('scoreboard').innerHTML = `<div class="match-team score-team ${win === 'A' ? 'winner' : ''}"><strong>${t('teamA')}</strong><span>${labelA}</span></div><div class="match-score score-numbers"><strong>${s.a}</strong><span>:</span><strong>${s.b}</strong></div><div class="match-team score-team ${win === 'B' ? 'winner' : ''}"><strong>${t('teamB')}</strong><span>${labelB}</span></div>`; show('matchIncompleteAlert', !complete); txt('matchIncompleteAlert', t('stillProgress')); }
function rankHtml(p) { const r = p?.rank || {}; const name = r.name || r.tierName || p?.rankName || '—'; const icon = r.icon || r.iconUrl; return `<span class="rank-mini">${icon ? `<img src="${esc(icon)}" alt="">` : ''}${esc(name)}</span>`; }
function avatar(p, cls='avatar sm') { return p?.avatarUrl ? `<img class="${cls}" src="${esc(p.avatarUrl)}" alt="${esc(p.nickname || 'Player avatar')}">` : `<span class="${cls} avatar-fallback" aria-label="${esc(p?.nickname || 'Player')}"></span>`; }
function playerRow(p) { const delta = eloDelta(p); const deltaText = TrustApi.formatEloChange(delta); return `<tr><th scope="row"><a class="player-name" href="${profileUrl(p)}">${avatar(p)}<span><strong>${esc(p.nickname || 'Unknown')}</strong>${p.steamId || p.steamId64 ? `<small>${esc(p.steamId || p.steamId64)}</small>` : ''}</span>${p.isMatchMvp ? '<span class="badge">MVP</span>' : ''}</a></th><td>${rankHtml(p)}</td><td>${TrustApi.safeNumber(p.kills,0)}</td><td>${TrustApi.safeNumber(p.deaths,0)}</td><td>${TrustApi.safeNumber(p.assists,0)}</td><td>${TrustApi.formatKd(p.kills,p.deaths)}</td><td>${TrustApi.safeNumber(p.headshots,0)}</td><td>${TrustApi.safeNumber(p.damage,0)}</td><td>${TrustApi.safeNumber(p.mvps ?? p.roundMvps,0)}</td><td>${TrustApi.safeNumber(p.firstKills,0)}</td><td>${TrustApi.safeNumber(p.clutches,0)}</td><td><span>${TrustApi.safeNumber(p.eloBefore,'—')} → ${TrustApi.safeNumber(p.eloAfter,'—')}</span><strong class="elo ${String(deltaText).startsWith('-')?'negative':'positive'}">${deltaText}</strong></td></tr>`; }
function mobilePlayerCard(p) { return `<article class="match-player-card"> <a class="player-name" href="${profileUrl(p)}">${avatar(p)}<strong>${esc(p.nickname || 'Unknown')}</strong>${p.isMatchMvp ? '<span class="badge">MVP</span>' : ''}</a><div class="mobile-player-primary"><span>K/D/A <strong>${TrustApi.safeNumber(p.kills,0)}/${TrustApi.safeNumber(p.deaths,0)}/${TrustApi.safeNumber(p.assists,0)}</strong></span><span>${t('damage')} <strong>${TrustApi.safeNumber(p.damage,0)}</strong></span><span>${t('eloChange')} <strong>${TrustApi.formatEloChange(eloDelta(p))}</strong></span></div><details><summary>${t('players')}</summary><div class="mobile-player-grid"><span>${t('kd')}: ${TrustApi.formatKd(p.kills,p.deaths)}</span><span>HS: ${TrustApi.safeNumber(p.headshots,0)}</span><span>MVP: ${TrustApi.safeNumber(p.mvps ?? p.roundMvps,0)}</span><span>FK: ${TrustApi.safeNumber(p.firstKills,0)}</span><span>${t('clutches')}: ${TrustApi.safeNumber(p.clutches,0)}</span>${rankHtml(p)}</div></details></article>`; }
function renderTeams(players) { if (!players.length) { $('matchTeams').innerHTML = `<section class="card empty">${t('detailedUnavailable')}</section>`; return; } const headers = ['PLAYER','RANK','K','D','A','K/D','HS','DMG','MVP','FK','CLUTCH','ELO']; $('matchTeams').innerHTML = ['A','B'].map((team) => { const list = players.filter((p) => teamOf(p) === team); return `<section class="card team-card"><div class="section-title"><h3>${team === 'A' ? t('teamA') : t('teamB')}</h3></div><table class="match-player-table"><thead><tr>${headers.map((h) => `<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${list.map(playerRow).join('')}</tbody></table><div class="match-player-cards">${list.map(mobilePlayerCard).join('') || `<div class="empty">${t('detailedUnavailable')}</div>`}</div></section>`; }).join(''); }
function renderMvp(players) { const mvp = players.filter((p) => p.isMatchMvp === true)[0]; show('matchMvpCard', true); $('matchMvpCard').innerHTML = mvp ? `<div class="match-mvp-card"><span class="badge">★ ${t('matchMvp')}</span><a href="${profileUrl(mvp)}" class="mvp-player">${avatar(mvp, 'profile-hero-avatar')}<div><h2>${esc(mvp.nickname || 'Unknown')}</h2><p class="muted">${teamOf(mvp) === 'A' ? t('teamA') : t('teamB')} · ${t('kills')}: ${TrustApi.safeNumber(mvp.kills,0)} · ${t('deaths')}: ${TrustApi.safeNumber(mvp.deaths,0)} · ${t('assists')}: ${TrustApi.safeNumber(mvp.assists,0)} · ${t('damage')}: ${TrustApi.safeNumber(mvp.damage,0)} · HS: ${TrustApi.safeNumber(mvp.headshots,0)} · ${t('clutches')}: ${TrustApi.safeNumber(mvp.clutches,0)} · ${TrustApi.formatEloChange(eloDelta(mvp))}</p></div></a></div>` : `<div class="empty">${t('mvpUnavailable')}</div>`; }
function renderRounds(rounds) { const list = Array.isArray(rounds) ? rounds : []; const filtered = roundFilter === 'all' ? list : list.filter((r) => String(r.winnerTeam || r.winner).toUpperCase() === roundFilter); $('roundStrip').innerHTML = filtered.length ? filtered.map((r, i) => { const w = String(r.winnerTeam || r.winner || '').toUpperCase(); const label = w === 'A' ? t('teamA') : w === 'B' ? t('teamB') : t('draw'); const a = TrustApi.safeNumber(r.teamAScore ?? r.scoreA, 0); const b = TrustApi.safeNumber(r.teamBScore ?? r.scoreB, 0); const reason = TrustApi.formatRoundReason(r.reason, r.reasonLabel, lang); return `<article class="round-card ${w === 'A' ? 'team-a' : 'team-b'}" aria-label="${esc(`${t('roundHistory')} ${i + 1}: ${label}, ${a}:${b}`)}"><strong>#${TrustApi.safeNumber(r.roundNumber, i + 1)}</strong><span>${label}</span><small>${a}:${b}</small><small>${esc(reason)}</small><small>${TrustApi.formatDuration(r.durationSeconds ?? r.durationSec)}</small></article>`; }).join('') : `<div class="empty">${t('detailedUnavailable')}</div>`; }
function render(m) { currentMatch = m; renderHero(m); const players = playersOf(m); renderMvp(players); renderTeams(players); renderRounds(m.rounds); }
function showError(err) { const notFound = err?.status === 404; txt('matchErrorBadge', notFound ? '404' : t('matchNotFound')); txt('matchErrorTitle', notFound ? t('matchNotFound') : (err?.message || t('matchNotFound'))); txt('matchErrorText', err?.message === 'invalid_id' ? t('invalidMatch') : (notFound ? t('matchNotFound') : t('invalidMatch'))); show('matchError', true); show('matchContent', false); }
async function load() { if (activeController) activeController.abort(); activeController = new AbortController(); currentMatch = null; show('matchLoading', true); show('matchError', false); show('matchContent', false); const id = new URLSearchParams(window.location.search).get('id'); if (!id || !/^[\w:-]{1,128}$/.test(id)) { show('matchLoading', false); showError(new Error('invalid_id')); return; } try { const data = await TrustApi.getMatchDetails(id, { signal: activeController.signal }); if (activeController.signal.aborted) return; render(data.match || data); show('matchContent', true); } catch (e) { if (e.name !== 'AbortError') showError(e); } finally { show('matchLoading', false); } }
document.addEventListener('DOMContentLoaded', () => { applyLang(); $('matchLangRu')?.addEventListener('click', () => { lang='ru'; localStorage.setItem(TrustApi.langKey, lang); applyLang(); }); $('matchLangEn')?.addEventListener('click', () => { lang='en'; localStorage.setItem(TrustApi.langKey, lang); applyLang(); }); $('matchRetryBtn')?.addEventListener('click', load); document.querySelectorAll('[data-round-filter]').forEach((b) => b.addEventListener('click', () => { roundFilter = b.dataset.roundFilter; document.querySelectorAll('[data-round-filter]').forEach((x) => x.classList.toggle('active', x === b)); renderRounds(currentMatch?.rounds || []); })); load(); });
window.addEventListener('beforeunload', () => activeController?.abort());
